"""added songs model

Revision ID: 05f8361e24f8
Revises: 8997a89be7e7
Create Date: 2022-04-24 10:30:22.139409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f8361e24f8'
down_revision = '8997a89be7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_name', sa.String(length=100), nullable=False),
    sa.Column('song_info', sa.String(), nullable=False),
    sa.Column('song_link', sa.String(), nullable=True),
    sa.Column('more_info', sa.String(), nullable=False),
    sa.Column('keysignature_id', sa.Integer(), nullable=False),
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composer_id'], ['composer.id'], ),
    sa.ForeignKeyConstraint(['keysignature_id'], ['keysignature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    # ### end Alembic commands ###
