"""empty message

Revision ID: 7a89e82ae5a6
Revises: 
Create Date: 2022-04-24 09:57:21.222200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a89e82ae5a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('era',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('era', sa.String(length=150), nullable=False),
    sa.Column('about_era', sa.String(), nullable=False),
    sa.Column('more_info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('era')
    )
    op.create_table('keysignature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_signature', sa.String(length=20), nullable=False),
    sa.Column('keys', sa.String(length=24), nullable=False),
    sa.Column('about', sa.String(), nullable=False),
    sa.Column('more_info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_signature')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))

    op.drop_table('user')
    op.drop_table('keysignature')
    op.drop_table('era')
    # ### end Alembic commands ###
