"""added composer with era backref

Revision ID: 8997a89be7e7
Revises: 7a89e82ae5a6
Create Date: 2022-04-24 10:24:34.275333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8997a89be7e7'
down_revision = '7a89e82ae5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composer_name', sa.String(length=100), nullable=False),
    sa.Column('more_info', sa.String(), nullable=True),
    sa.Column('famous_work', sa.String(), nullable=True),
    sa.Column('era_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['era_id'], ['era.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('composer_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('composer')
    # ### end Alembic commands ###
