"""small changes

Revision ID: a90a17bb8fbf
Revises: 05f8361e24f8
Create Date: 2022-04-24 12:07:41.954137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90a17bb8fbf'
down_revision = '05f8361e24f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.drop_column('famous_work')

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(), nullable=True))
        batch_op.alter_column('more_info',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('more_info',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('difficulty')

    with op.batch_alter_table('composer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('famous_work', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
